{
 "title": "Node Exporter Dashboard",
 "description": "A quickstart to setup Prometheus Node Exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{job=\"kubernetes-service-endpoints\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods on node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by (pod)(kube_pod_info{node=\"$node\"})",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Node IP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$node\", app_kubernetes_io_instance=\"kube-state-metrics\"}",
     "legendFormat": "{{internal_ip}}"
    }
   ]
  },
  {
   "title": "Node ID",
   "type": "stat",
   "description": "Shows\nCloud/region/subnet/instance-id",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$node\", app_kubernetes_io_instance=\"kube-state-metrics\"}",
     "legendFormat": "{{provider_id}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU usage total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(node) (irate(node_cpu_seconds_total{node=\"$node\", mode!=\"idle\"}[5m])) / on(node) group_left sum by (node)((irate(node_cpu_seconds_total{node=\"$node\"}[5m])))) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"kubernetes-service-endpoints\", node=\"$node\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"kubernetes-service-endpoints\", node=\"$node\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"kubernetes-service-endpoints\", node=\"$node\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"kubernetes-service-endpoints\", node=\"$node\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\"}\n-\n  node_memory_MemFree_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\"}\n-\n  node_memory_Buffers_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\"}\n-\n  node_memory_Cached_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\"}",
     "legendFormat": "memory free"
    },
    {
     "expr": "  node_memory_MemTotal_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\"}\n",
     "legendFormat": "Memory total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{node=\"$node\"} * 100) / node_memory_MemTotal_bytes{node=\"$node\"})",
     "legendFormat": "MemoryUsage:"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\", fstype!=\"\"}\n  -\n    node_filesystem_avail_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{job=\"kubernetes-service-endpoints\", node=\"$node\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  }
 ]
}