{
 "title": "kubernetes - pod-node - overview",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{ pod=~\"$pod\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(node) (irate(node_cpu_seconds_total{node=\"$node\", mode!=\"idle\"}[5m])) / on(node) group_left sum by (node)((irate(node_cpu_seconds_total{node=\"$node\"}[5m])))) * 100",
     "legendFormat": "CPUusage: {{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{node=\"$node\"} * 100) / node_memory_MemTotal_bytes{node=\"$node\"})",
     "legendFormat": "Memory usage:"
    }
   ]
  },
  {
   "title": "Pods on Node",
   "type": "timeseries",
   "description": "All the pods that are running on the selected node",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "group by (pod)(kube_pod_info{node=\"$node\"})",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Pod count on Node",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$node\", app_kubernetes_io_component!=\"\"})"
    }
   ]
  },
  { "title": "POD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Pod CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"$pod\",container_name=~\"$container\",container_name!=\"POD\",image!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(rate(container_cpu_usage_seconds_total{pod_name=~\"$pod\", container_name=~\"$container\", image!=\"\", container_name!=\"POD\", image!=\"\"}[5m]))",
     "legendFormat": "ContainerUsage: {{ container_name }}"
    },
    {
     "expr": "avg by(pod) (kube_pod_container_resource_requests{unit=\"core\", resource=\"cpu\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Requested: {{ pod }}"
    },
    {
     "expr": "avg by(pod) (kube_pod_container_resource_limits{unit=\"core\", resource=\"cpu\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod_name=~\"$pod\",container_name=~\"$container\", container_name!=\"POD\", container_name!=\"\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container_name) (container_memory_working_set_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\",container_name!=\"\",image!=\"\"})",
     "legendFormat": "ContainerUsage: {{ container_name }}"
    },
    {
     "expr": "avg by(pod) (kube_pod_container_resource_requests{unit=\"byte\", resource=\"memory\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Request: {{ pod }}"
    },
    {
     "expr": "avg by(pod) (kube_pod_container_resource_limits{unit=\"byte\", resource=\"memory\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Pods in namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Pod restarts by namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (namespace)(changes(kube_pod_status_ready{condition=\"true\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods not ready by namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 37 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_status_ready{condition=\"false\"})\n"
    }
   ]
  }
 ]
}