fullnameOverride: "flask-api-server"

replicaCount: 1

image:
  repository: kennethreitz/httpbin
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000  # Flask default port

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

env: []  # Add your environment variables here if needed

serviceAccount:
  create: false
  name: ""
  

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "nadav-proj-cluster-ext-alb-1530607942.us-east-2.elb.amazonaws.com"
      paths:
        - path: "/testing"
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70