---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-nai-advanced-ext-naturalint-com
  namespace: nai-advanced
spec:
  secretName: wildcard-nai-advanced-ext-naturalint-com-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '*.nai-advanced-ext.naturalint.com'
  dnsNames:
    - '*.nai-advanced-ext.naturalint.com'